# Generated by Django 3.2 on 2021-05-23 11:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('author', models.CharField(max_length=50)),
                ('ISBN', models.CharField(max_length=13, unique=True)),
                ('book_amount', models.IntegerField(default=0)),
                ('popularity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a book genre', max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('popularity', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'BookGenres',
            },
        ),
        migrations.CreateModel(
            name='FilmGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a book genre', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BookRentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_date', models.DateField(auto_now_add=True)),
                ('back_date', models.DateField(default=datetime.datetime(2021, 6, 22, 13, 20, 9, 189956))),
                ('book', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='rental.book')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rental.bookgenre'),
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=50)),
                ('length', models.DecimalField(decimal_places=2, max_digits=3)),
                ('borrowed', models.BooleanField(default=False)),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rental.filmgenre')),
            ],
            options={
                'unique_together': {('director', 'title', 'length')},
            },
        ),
        migrations.CreateModel(
            name='CD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=30)),
                ('tracks', models.TextField()),
                ('length', models.DecimalField(decimal_places=2, max_digits=3)),
                ('borrowed', models.BooleanField(default=False)),
                ('whoAdd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('genre', 'tracks')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('author', 'title', 'genre')},
        ),
    ]
