# Generated by Django 3.2 on 2021-05-24 20:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('author', models.CharField(max_length=50)),
                ('ISBN', models.CharField(max_length=13, unique=True)),
                ('book_amount', models.IntegerField(default=0)),
                ('popularity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a book genre', max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('popularity', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'BookGenres',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('length', models.DecimalField(decimal_places=2, max_digits=3)),
                ('film_amount', models.IntegerField(default=0)),
                ('popularity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FilmGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a film genre', max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('popularity', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'FilmGenres',
            },
        ),
        migrations.CreateModel(
            name='FilmRentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_date', models.DateField(auto_now_add=True)),
                ('back_date', models.DateField(default=datetime.datetime(2021, 6, 23, 22, 13, 27, 814386))),
                ('film', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='rental.film')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='films', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rental.filmgenre'),
        ),
        migrations.CreateModel(
            name='BookRentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_date', models.DateField(auto_now_add=True)),
                ('back_date', models.DateField(default=datetime.datetime(2021, 6, 23, 22, 13, 27, 813389))),
                ('book', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='rental.book')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rental.bookgenre'),
        ),
        migrations.AlterUniqueTogether(
            name='film',
            unique_together={('director', 'title', 'length')},
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('author', 'title', 'genre')},
        ),
    ]
