# Generated by Django 3.2 on 2021-05-29 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrenthistory',
            name='back_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 28, 20, 27, 4, 778702)),
        ),
        migrations.AlterField(
            model_name='cdrenthistory',
            name='back_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 28, 20, 27, 4, 781692)),
        ),
        migrations.AlterField(
            model_name='filmrenthistory',
            name='back_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 28, 20, 27, 4, 779693)),
        ),
    ]
