# Generated by Django 2.2.22 on 2021-05-15 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rental', '0002_film'),
    ]

    operations = [
        migrations.CreateModel(
            name='CD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=30)),
                ('tracks', models.TextField()),
                ('length', models.DecimalField(decimal_places=2, max_digits=19)),
                ('borrowed', models.BooleanField(default=False)),
                ('whoAdd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
