# Generated by Django 3.2 on 2021-05-26 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0022_auto_20210526_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrenthistory',
            name='back_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 25, 21, 49, 12, 554701)),
        ),
        migrations.AlterField(
            model_name='cdrenthistory',
            name='back_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 25, 21, 49, 12, 557693)),
        ),
        migrations.AlterField(
            model_name='filmrenthistory',
            name='back_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 25, 21, 49, 12, 555698)),
        ),
    ]
